[OT276-24] Endpoint datos públicos de la Organización
alkemyTech/OT276-server pull request #26
Opened 2022-08-29 16:32 UTC by Juanchini23

## Why is this change required?

### Motivation and Summary
COMO anonimo
QUIERO ver los datos de una Organización
PARA tener conocimiento sobre ella.

Criterios de aceptación: 

Se debe realizar una petición GET hacia ruta /organization/public

El endpoint debe devolver solamente los campos name, image, phone y address de la Organización

### Type of change
- [x ] New feature
- [ ] Bug fix
- [ ] New Tests (no functional change)
- [ ] Refactor (no functional change)

### Checklist

- [ ] Traceability between this change and Jira.
- [ ] ```mvn clean install``` was run and all tests completed successfully.
- [ ] There are no unused variables and/or imports in the modified classes.
- [ ] There are no imports in the modified classes with the wildcard character. Ex: ```com.somepackage.*```.
- [ ] Slf4j was used for the application log instead ```System.out```.
- [ ] Public methods are documented with ```javadoc```.

2022-08-30 11:58 UTC, manerajona requested changes

2022-08-30 11:58 UTC, manerajona commented on src/main/java/com/alkemy/ong/config/SecurityConfig.java
> +                .antMatchers("/api/docs/**", "/api/swagger-ui/**", "/v3/api-docs/**", "/auth/login", "/auth/register", "/v1/organizations/public/**").permitAll()
Deberíamos agregarlo con el método para evitar que cualquier POST, PUT, DELETE quede expuesto y sacar el matcher `**` ya que debemos hacerlo lo más especifico posible pare evitar security leaks.

`.antMatchers(HttpMethod.GET, "/v1/organizations/public").permitAll()`

2022-08-30 11:58 UTC, manerajona commented on src/main/java/com/alkemy/ong/core/model/Organization.java
> +import javax.persistence.*;
Por favor revertir estos cambios, es una mala práctica utilizar imports con asterisco.

2022-08-30 11:58 UTC, manerajona commented on src/main/java/com/alkemy/ong/core/usecase/impl/OrganizationServiceImpl.java
> +    private final OrganizationRepository repoOrganization;
Por favor utilizar el nombre más estandar que sería organizationRepository. (está españolizado)

2022-08-30 11:58 UTC, manerajona commented on src/main/java/com/alkemy/ong/core/usecase/impl/OrganizationServiceImpl.java
> +    @Override
Agregar `@Transactional(readOnly = true)`

2022-08-30 11:58 UTC, manerajona commented on src/main/java/com/alkemy/ong/ports/input/rs/api/OrganizationApi.java
> +@SecurityRequirement(name = "bearerAuth")
Sacarle por favor el `@SecurityRequirement(name = "bearerAuth")` ya que no van a estar todos los endpoints securizados.

2022-08-30 11:58 UTC, manerajona commented on src/main/java/com/alkemy/ong/ports/input/rs/api/OrganizationApi.java
> +            @ApiResponse(responseCode = "204", description = "No Content")
La respuesta es OK con un response body, no 204

2022-08-30 11:58 UTC, manerajona commented on src/main/java/com/alkemy/ong/ports/input/rs/controller/OrganizationController.java
> +    private final OrganizationService serviceOrganization;
Igual que en caso del repo está españolizado, seria organizationService o simplemente service.

2022-08-30 11:58 UTC, manerajona commented on src/main/java/com/alkemy/ong/ports/input/rs/response/OrganizationResponse.java
> +    //nombre imagen teleofno y direccion
Borrar este comentario por favor

2022-08-31 12:32 UTC, Juanchini23 commented on src/main/java/com/alkemy/ong/config/SecurityConfig.java
> +                .antMatchers("/api/docs/**", "/api/swagger-ui/**", "/v3/api-docs/**", "/auth/login", "/auth/register", "/v1/organizations/public/**").permitAll()
Hecho

2022-08-31 12:38 UTC, Juanchini23 commented on src/main/java/com/alkemy/ong/core/model/Organization.java
> +import javax.persistence.*;
Hecho, se genera automaticamente el import con * y no lo habia notado

2022-08-31 12:44 UTC, Juanchini23 commented on src/main/java/com/alkemy/ong/core/usecase/impl/OrganizationServiceImpl.java
> +    private final OrganizationRepository repoOrganization;
Hecho

2022-08-31 12:46 UTC, Juanchini23 commented on src/main/java/com/alkemy/ong/core/usecase/impl/OrganizationServiceImpl.java
> +    @Override
Hecho

2022-08-31 12:51 UTC, Juanchini23 commented on src/main/java/com/alkemy/ong/ports/input/rs/response/OrganizationResponse.java
> +    //nombre imagen teleofno y direccion
Todos los cambios hechos!

2022-08-31 15:52 UTC, merged