Feature/ot276 25
alkemyTech/OT276-server pull request #27
Opened 2022-08-29 17:07 UTC by Yeyini7615

## Why is this change required?

### Motivation and Summary
COMO usuario
QUIERO registrarme en el sistema
PARA ser parte del mismo

Criterios de aceptación:

Se debe hacer una petición POST /auth/register 

El endpoint deberá validar los campos Nombre, Apellido, Email, Contraseña. 

La contraseña debe ser encriptada. 

Deberá devolver como respuesta el usuario generado.

Para las validaciones, se deben utilizar Annotations en los modelos.

Validar

Encriptar contraseña

Almacenar en base de datos

### Type of change
- [X] New feature
- [ ] Bug fix
- [ ] New Tests (no functional change)
- [ ] Refactor (no functional change)

### Checklist

- [ ] Traceability between this change and Jira.
- [ ] ```mvn clean install``` was run and all tests completed successfully.
- [ ] There are no unused variables and/or imports in the modified classes.
- [ ] There are no imports in the modified classes with the wildcard character. Ex: ```com.somepackage.*```.
- [ ] Slf4j was used for the application log instead ```System.out```.
- [ ] Public methods are documented with ```javadoc```.

2022-08-30 13:31 UTC, manerajona commented
@Yeyini7615 porfa resolver conflictos

2022-08-30 14:17 UTC, Yeyini7615 commented
@manerajona  Conflictos resueltos, register y login funcionando en esta rama.

2022-08-31 16:16 UTC, manerajona requested changes

2022-08-31 16:16 UTC, manerajona commented on src/main/java/com/alkemy/ong/config/CryptoConfig.java
> +
No subir este cambio por favor

2022-08-31 16:16 UTC, manerajona commented on src/main/java/com/alkemy/ong/core/model/User.java
> +import javax.persistence.*;
No utilizar * en imports

2022-08-31 16:16 UTC, manerajona commented on src/main/java/com/alkemy/ong/ports/input/rs/controller/AuthController.java
> +        if (userService.exist(userRequest.getEmail())) {
Esta validación de email se debe hacer en el Service

2022-08-31 16:16 UTC, manerajona commented on src/main/java/com/alkemy/ong/ports/input/rs/controller/UserController.java
> +public class UserController  {
No subir esta clase por favor

2022-08-31 16:16 UTC, manerajona commented on src/main/resources/application.properties
> -#spring.datasource.password=password
No subir este cambio por favor

2022-08-31 16:16 UTC, manerajona commented on src/main/java/com/alkemy/ong/core/usecase/impl/UserServiceImpl.java
> +        user.setPassword(passwordEncoder.encode(user.getPassword()));
Por favor antes de nada validar la existencia del usuario por email y en caso de que exista se lanza una excepción por conflicto:

```java
if (exist(user.getEmail())) {
            throw new ConflictException(
                    "There is already an account with that email address: " + user.getEmail()
            );
        }
```

2022-08-31 16:16 UTC, manerajona commented on src/main/java/com/alkemy/ong/core/usecase/impl/UserServiceImpl.java
> +        user.setRole(roleRepository.findById(1L).get());
Sacar el rol de la variable `default.role.id` en el `application.properties` por favor

2022-08-31 16:16 UTC, manerajona commented on src/main/java/com/alkemy/ong/core/usecase/impl/UserServiceImpl.java
> +        return userRepository.save(user).getId();
Antes del return hacer el envío del email de bienvenida:

```java
emailService.sendWelcomeEmail(
                organizationRepository.findById(defaultOrganizationId).get(),
                user.getEmail());
```

defaultOrganizationId está en la variable `default.organization.id` del `application.properties`

2022-08-31 16:16 UTC, manerajona commented
@Yeyini7615 resolver los conflictos porfavor

2022-09-01 20:36 UTC, manerajona commented on src/main/java/com/alkemy/ong/core/usecase/UserService.java
> +    Boolean exist(String email);
Por favor este metodo hacerlo privado de la clase

2022-09-01 20:36 UTC, manerajona commented on src/main/java/com/alkemy/ong/core/model/User.java
> +import javax.persistence.*;
Recordad no usar * (hacer un click derecho y seleccionar "optimize imports")

2022-09-01 20:36 UTC, manerajona commented on src/main/java/com/alkemy/ong/ports/input/rs/request/CreateUserRequest.java
> +    @JsonProperty("firstName")
Usar snake_case en json prop: first_name

2022-09-01 20:36 UTC, manerajona commented on src/main/java/com/alkemy/ong/ports/input/rs/request/CreateUserRequest.java
> +    @JsonProperty("lastName")
last_name

2022-09-01 20:37 UTC, manerajona requested changes

2022-09-01 20:37 UTC, manerajona commented on src/main/java/com/alkemy/ong/core/usecase/impl/UserServiceImpl.java
> +    public Boolean exist(String email) {
Hacerlo private

2022-09-01 21:45 UTC, merged