[OT276-36] Endpoint para listar Usuarios
alkemyTech/OT276-server pull request #28
Opened 2022-08-29 21:55 UTC by Juacun

## Why is this change required?

### Motivation and Summary
COMO usuario administrador
QUIERO visualizar un listado de Usuarios
PARA mantener un seguimiento de quiénes forman parte del sistema

Criterios de aceptación:
GET a /users . Devolverá un listado de todos los Usuarios. Este endpoint solo deberá ser accesible por los Usuarios administradores.

### Type of change
- [ ] New feature
- [ ] Bug fix
- [ ] New Tests (no functional change)
- [ ] Refactor (no functional change)

### Checklist

- [ ] Traceability between this change and Jira.
- [ ] ```mvn clean install``` was run and all tests completed successfully.
- [ ] There are no unused variables and/or imports in the modified classes.
- [ ] There are no imports in the modified classes with the wildcard character. Ex: ```com.somepackage.*```.
- [ ] Slf4j was used for the application log instead ```System.out```.
- [ ] Public methods are documented with ```javadoc```.

2022-08-30 13:12 UTC, manerajona requested changes

2022-08-30 13:12 UTC, manerajona commented on src/main/java/com/alkemy/ong/ports/input/rs/controller/UserController.java
> +            response.add(mapper.userToUserResponse(entity));
Agregar al mapper un método para mapear de lista a lista y borrar el for. Debería ser algo así:

List<UserResponse> userListToUserResponseList(List<User> list);

2022-08-30 13:43 UTC, Juacun commented on src/main/java/com/alkemy/ong/ports/input/rs/controller/UserController.java
> +            response.add(mapper.userToUserResponse(entity));
Listo!

2022-08-30 19:01 UTC, manerajona requested changes

2022-08-30 19:01 UTC, manerajona commented on src/main/java/com/alkemy/ong/ports/input/rs/controller/UserController.java
> +import java.util.ArrayList;
por favor borrar esta dependencia

2022-08-30 19:01 UTC, manerajona commented on src/main/java/com/alkemy/ong/ports/input/rs/mapper/UserControllerMapper.java
> +    @Named("userListToUserResponseList")
Para que utilice el mapper definido en la linea 14 agregar:

`@IterableMapping(qualifiedByName = "userToUserResponse")`

(sino crea otro método que hace lo mismo y lo llama `userToUserResponse1`

2022-08-31 00:19 UTC, Juacun commented on src/main/java/com/alkemy/ong/ports/input/rs/controller/UserController.java
> +import java.util.ArrayList;
Listo!

2022-08-31 00:29 UTC, Juacun commented on src/main/java/com/alkemy/ong/ports/input/rs/mapper/UserControllerMapper.java
> +    @Named("userListToUserResponseList")
Listo!

2022-08-31 16:00 UTC, merged