Endpoint Actualización Miembros
alkemyTech/OT276-server pull request #32
Opened 2022-08-30 23:30 UTC by matiaguro

## Why is this change required?
Descripción

COMO usuario
QUIERO actualizar los Miembros
PARA mantener la información actualizada.

Criterios de aceptación:
PUT /members/:id - Deberá validar que el miembro existe y actualizarla, caso contrario devolver un error
### Motivation and Summary

### Type of change
- [ ] New feature
- [ ] Bug fix
- [ ] New Tests (no functional change)
- [ ] Refactor (no functional change)

### Checklist

- [ ] Traceability between this change and Jira.
- [ ] ```mvn clean install``` was run and all tests completed successfully.
- [ ] There are no unused variables and/or imports in the modified classes.
- [ ] There are no imports in the modified classes with the wildcard character. Ex: ```com.somepackage.*```.
- [ ] Slf4j was used for the application log instead ```System.out```.
- [ ] Public methods are documented with ```javadoc```.

2022-09-01 12:40 UTC, manerajona commented
@matiaguro por favor resolver conflictos con main

2022-09-01 23:37 UTC, matiaguro commented
@manerajona Conflictos solucionados!

2022-09-02 16:41 UTC, manerajona requested changes

2022-09-02 16:41 UTC, manerajona commented on src/main/java/com/alkemy/ong/ports/input/rs/mapper/MemberControllerMapper.java
> +    Member updateMemberRequestToMember(MemberRequest memberRequest);
Este método hace lo mismo que el de arriba, podríamos hacer uno solo que sea `memberRequestToMember`

2022-09-02 16:41 UTC, manerajona commented on src/main/java/com/alkemy/ong/ports/input/rs/controller/MemberController.java
> +
Falta una llave `}`

2022-09-02 16:43 UTC, manerajona commented
@matiaguro no te olvides de agregar en SpringSecurity esto para que el usuario pueda actualizar:

.antMatchers(HttpMethod.PUT, ApiConstants.MEMBERS_URI + "/{id}").authenticated()

2022-09-02 16:44 UTC, manerajona requested changes

2022-09-02 16:44 UTC, manerajona commented on src/main/java/com/alkemy/ong/ports/input/rs/controller/MemberController.java
> +    @PutMapping("/{id}")
Falta el import de `PutMapping`

2022-09-05 14:05 UTC, merged