Crear modelo y repositorio base de Members
alkemyTech/OT276-server pull request #4
Opened 2022-08-18 22:43 UTC by matiaguro

## Why is this change required?
COMO desarrollador 
QUIERO agregar la entidad Member
PARA representar en la implementación la estructura de datos

Criterios de aceptación: 
Nombre de tabla: members. Campos:
name: VARCHAR NOT NULL
facebookUrl: VARCHAR NULLABLE
instagramUrl: VARCHAR NULLABLE
linkedinUrl: VARCHAR NULLABLE
image: VARCHAR NOT NULL
description: VARCHAR NULLABLE
timestamps y softDelete
### Motivation and Summary

### Type of change
- [ x] New feature
- [ ] Bug fix
- [ ] New Tests (no functional change)
- [ ] Refactor (no functional change)

### Checklist

- [ x] Traceability between this change and Jira.
- [ ] ```mvn clean install``` was run and all tests completed successfully.
- [ ] There are no unused variables and/or imports in the modified classes.
- [ ] There are no imports in the modified classes with the wildcard character. Ex: ```com.somepackage.*```.
- [ ] Slf4j was used for the application log instead ```System.out```.
- [ ] Public methods are documented with ```javadoc```.

2022-08-19 18:57 UTC, manerajona requested changes
Por favor probar que levante la aplicación @matiaguro

2022-08-19 18:57 UTC, manerajona commented on src/main/resources/db/migration/V1.00.1__create_table_member.sql
> +drop table if exist member;
Por favor cambiar el nombre del script a: V1.23__create_table_member.sql

2022-08-19 18:57 UTC, manerajona commented on src/main/resources/db/migration/V1.00.1__create_table_member.sql
> +drop table if exist member;
Por favor utilizar la sentencia `exists`, exist no existe.

2022-08-19 18:57 UTC, manerajona commented on src/main/resources/db/migration/V1.00.1__create_table_member.sql
> +    {
No se utilizan llaves al crear scripts sql, usar paréntesis `()`

2022-08-19 18:57 UTC, manerajona commented on src/main/resources/db/migration/V1.00.1__create_table_member.sql
> +    facebookUrl     varchar(255)   nullable,
Remover todas la sentencias `nullable` por favor

2022-08-19 18:57 UTC, manerajona commented on src/main/resources/db/migration/V1.00.1__create_table_member.sql
> +    updated_at      datetime(6)    null
falta una coma al final del statement

2022-08-19 18:57 UTC, manerajona commented on src/main/resources/db/migration/V1.00.1__create_table_member.sql
> +    facebookUrl     varchar(255)   nullable,
Las columnas de la tabla van en snake_case no camelCase.

2022-08-23 23:05 UTC, matiaguro commented
Se corrigieron los errores marcados

2022-08-23 23:06 UTC, matiaguro commented
@manerajona

2022-08-24 13:36 UTC, merged