[OT276-59] Endpoint Actualización Slides
alkemyTech/OT276-server pull request #62
Opened 2022-09-09 03:43 UTC by wilux

## Why is this change required?

### Motivation and Summary
COMO usuario administrador
QUIERO poder actualizar Slides 
PARA tener la información actualizada al comienzo de la página

Criterios de aceptación:

Se debe hacer una petición PUT /Slides/:id 

Deberá validar que el slide existe y actualizarlo, caso contrario devolver un error.

### Type of change
- [x] New feature
- [ ] Bug fix
- [ ] New Tests (no functional change)
- [ ] Refactor (no functional change)

### Checklist

- [ ] Traceability between this change and Jira.
- [ ] ```mvn clean install``` was run and all tests completed successfully.
- [ ] There are no unused variables and/or imports in the modified classes.
- [ ] There are no imports in the modified classes with the wildcard character. Ex: ```com.somepackage.*```.
- [ ] Slf4j was used for the application log instead ```System.out```.
- [ ] Public methods are documented with ```javadoc```.

2022-09-09 20:00 UTC, manerajona commented
@wilux corregir conflictos porfa

2022-09-13 17:32 UTC, manerajona requested changes

2022-09-13 17:32 UTC, manerajona commented on src/main/java/com/alkemy/ong/core/usecase/impl/SlideServiceImpl.java
> +        }
Indentar esta llave con el método por favor.

Hacer un `reformat code`
<img width="509" alt="image" src="https://user-images.githubusercontent.com/21185543/189968926-1b66c684-3f67-41d9-84a2-1c1326804434.png">

2022-09-13 17:32 UTC, manerajona commented on src/main/java/com/alkemy/ong/core/usecase/impl/SlideServiceImpl.java
> +        Slide slide = new Slide();
En vez de crear un Slide con el constructor vacío: 

1. Hacer un `Slide slide = slideRepository.findById(id).orElseThrow(() -> new NotFoundException(id));`

2. setear los valores.

3. guardar `slideRepository.save(slide);`

Además, lanzar la exception después de subir la imagen a amazon no es correcto, tiene que validarse antes.

2022-09-13 21:18 UTC, manerajona requested changes

2022-09-13 21:18 UTC, manerajona commented on src/main/java/com/alkemy/ong/core/usecase/impl/SlideServiceImpl.java
> +            Organization organization;
Podemos colocar la declaración de la variable junto a la asignación para simplificar por favor

2022-09-13 21:18 UTC, manerajona commented on src/main/java/com/alkemy/ong/core/usecase/impl/SlideServiceImpl.java
> +        if (text != null) {
No validar si text es nulo, ya que es un método PUT y debe ser remplazado. Si hay que hacer alguna validación de no-nulidad hacerla en el request.

2022-09-13 21:18 UTC, manerajona commented on src/main/java/com/alkemy/ong/core/usecase/impl/SlideServiceImpl.java
> +        } else slide.setOrder(slide.getOrder());
¿Este if no va en la linea 93?

2022-09-13 21:18 UTC, manerajona commented on src/main/java/com/alkemy/ong/core/usecase/impl/SlideServiceImpl.java
> +        slide.setImageUrl(slide.getImageUrl());
Esto es redundante, hacer un else donde se asigne null en la linea 84 por favor

2022-09-13 21:18 UTC, manerajona commented on src/main/java/com/alkemy/ong/core/usecase/impl/SlideServiceImpl.java
> +        slide.setOrganization(slide.getOrganization());
Esto tambien es redundante

2022-09-13 22:50 UTC, wilux commented on src/main/java/com/alkemy/ong/core/usecase/impl/SlideServiceImpl.java
> +        } else slide.setOrder(slide.getOrder());
Si!,   No se como llego hasta ahí, dios mío! jaja.

2022-09-14 12:48 UTC, manerajona requested changes

2022-09-14 12:48 UTC, manerajona commented on src/main/java/com/alkemy/ong/core/usecase/impl/SlideServiceImpl.java
> +        slide.setImageUrl(slide.getImageUrl());
Aca se tiene que setear null si la `imageBase64 == null`

2022-09-14 12:48 UTC, manerajona commented on src/main/java/com/alkemy/ong/core/usecase/impl/SlideServiceImpl.java
> +        slide.setOrganization(slide.getOrganization());
Acá se tiene que setear null si `organizationId == null`. No tiene sentido hacer un set de un get del mismo objeto.

2022-09-14 14:02 UTC, merged