[OT276-79] Endpoint Eliminación Comentarios
alkemyTech/OT276-server pull request #66
Opened 2022-09-12 19:01 UTC by Juanchini23

## Why is this change required?

### Motivation and Summary
COMO usuario
QUIERO borrar un comentario
PARA moderar el contenido

Criterios de aceptación:
DELETE /comments/:id - Deberá validar la existencia del comentario. Solamente podrán eliminar un comentario el usuario creador del mismo o un administrador. Deberá devolver un código 403 si no tiene permiso para modificarlo.
### Type of change
- [X] New feature
- [ ] Bug fix
- [ ] New Tests (no functional change)
- [ ] Refactor (no functional change)

### Checklist

- [ ] Traceability between this change and Jira.
- [ ] ```mvn clean install``` was run and all tests completed successfully.
- [ ] There are no unused variables and/or imports in the modified classes.
- [ ] There are no imports in the modified classes with the wildcard character. Ex: ```com.somepackage.*```.
- [ ] Slf4j was used for the application log instead ```System.out```.
- [ ] Public methods are documented with ```javadoc```.

2022-09-12 19:29 UTC, manerajona requested changes

2022-09-12 19:29 UTC, manerajona commented on src/main/java/com/alkemy/ong/core/usecase/impl/CommentServiceImpl.java
> +    public void deleteEntityById(Long id, User user) {
Agregar @Transactional por favor

2022-09-12 19:29 UTC, manerajona commented on src/main/java/com/alkemy/ong/ports/input/rs/api/CommentApi.java
>      ResponseEntity<Void> createEntity(@Valid CreateCommentRequest createCommentRequest, @AuthenticationPrincipal User user);
Agregar `@Parameter(name = "user", hidden = true)` por favor a los métodos que usan AuthenticationPrincipal

2022-09-13 02:03 UTC, Juanchini23 commented on src/main/java/com/alkemy/ong/ports/input/rs/api/CommentApi.java
>      ResponseEntity<Void> createEntity(@Valid CreateCommentRequest createCommentRequest, @AuthenticationPrincipal User user);
Hechos!

2022-09-13 17:13 UTC, merged