[OT276-29] Crear modelo y repositorio de Slides.
alkemyTech/OT276-server pull request #8
Opened 2022-08-19 15:12 UTC by Yeyini7615

## Why is this change required?

### Motivation and Summary
COMO usuario administrador
QUIERO gestionar las imágenes
PARA modificar eficientemente el contenido visual

Criterios de aceptación:

Los Slides de la pantalla de inicio serán gestionados de forma dinámica por el administrador del sitio. 

Los mismos tendrán como campos imageUrl, text, order y organizationId (ya que pertenecerán una ONG).

### Type of change
- [x] New feature
- [ ] Bug fix
- [ ] New Tests (no functional change)
- [ ] Refactor (no functional change)

### Checklist

- [ ] Traceability between this change and Jira.
- [ ] ```mvn clean install``` was run and all tests completed successfully.
- [ ] There are no unused variables and/or imports in the modified classes.
- [ ] There are no imports in the modified classes with the wildcard character. Ex: ```com.somepackage.*```.
- [ ] Slf4j was used for the application log instead ```System.out```.
- [ ] Public methods are documented with ```javadoc```.

2022-08-19 20:26 UTC, manerajona commented
@Yeyini7615 ya está mergeado el model y repo de Organization

2022-08-19 22:50 UTC, Yeyini7615 commented
@manerajona esta rama tiene el model, repo y script de Slide, probe que funcionaba antes de hacer el commit. Hice el pull de main con con los cambios y mergie esta rama y todo ok. Hago commit de esa nueva rama con todo o dejo esta que es solo lo del ticket?

2022-08-20 14:31 UTC, manerajona commented
> @manerajona esta rama tiene el model, repo y script de Slide, probe que funcionaba antes de hacer el commit. Hice el pull de main con con los cambios y mergie esta rama y todo ok. Hago commit de esa nueva rama con todo o dejo esta que es solo lo del ticket?

Exacto, si ya te bajaste lo que te hacia falta de main comitea todos los cambios en esta rama así se actualiza el pull-request.

2022-08-20 21:16 UTC, Yeyini7615 commented
@manerajona Listo para subir a main.

2022-08-20 22:17 UTC, manerajona requested changes

2022-08-20 22:17 UTC, manerajona commented on src/main/java/com/alkemy/ong/core/model/Activity.java
> +public class Activity implements Auditable {
Fijate que estos archivos no deberías subirlo

2022-08-20 22:17 UTC, manerajona commented on src/main/java/com/alkemy/ong/core/model/Testimonial.java
> +public class Testimonial implements Auditable {
igual que el comentario anterior

2022-08-20 22:17 UTC, manerajona commented on src/main/java/com/alkemy/ong/core/repository/ActivityRepository.java
> +public interface ActivityRepository extends PagingAndSortingRepository<Activity, Long> {
igual que el comentario anterior

2022-08-20 22:17 UTC, manerajona commented on src/main/java/com/alkemy/ong/core/repository/TestimonialRepository.java
> +public interface TestimonialRepository extends JpaRepository<Testimonial, Long> {
igual que el comentario anterior

2022-08-20 22:17 UTC, manerajona commented on src/main/resources/db/migration/V1.21__create_table_testimonial.sql
> +create table testimonial
igual que el comentario anterior

2022-08-20 22:17 UTC, manerajona commented on src/main/resources/db/migration/V1.22__create_table_activityl.sql
> +create table activity
igual que el comentario anterior

2022-08-20 22:26 UTC, Yeyini7615 commented
@manerajona Commit realizado solo con modelos Organization y Slide.

2022-08-22 17:55 UTC, manerajona requested changes

2022-08-22 17:55 UTC, manerajona commented on src/main/resources/db/migration/V1.29__create_table_slide.sql
> +    o_rder          int            not null,
podríamos ponerle `slide_order` para que quede más significativo

2022-08-22 17:55 UTC, manerajona commented on src/main/java/com/alkemy/ong/core/model/Slide.java
> +    @ManyToOne(cascade = CascadeType.ALL, fetch = FetchType.LAZY)
Sacar el cascade = cascadeType.ALL por favor, ya que sino cada vez que borremos una slide se va a borrar la organization.

2022-08-22 18:14 UTC, merged